name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.10.0
  - requests=2.26.0
  - pip=23.3.1
  - mlflow=2.8.1
  - hydra-core=1.3.2
  - protobuf>=3.20.3,<3.21.0
  - pyarrow=14.0.2
  - libprotobuf>=3.20.3,<3.21.0
  - arrow-cpp=14.0.2
  - scikit-learn=1.4.1
  - omegaconf=2.3
  
  - pip:
      - wandb==0.18.3
      - hydra-joblib-launcher==1.1.2
      - databricks_cli==0.8.7
