_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
